# Generated by Django 5.2.17 on 2026-09-16 04:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("batch_code", models.CharField(max_length=40, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("IN_PROGRESS", "In progress"),
                            ("MATURING", "Maturing"),
                            ("AVAILABLE", "Available"),
                            ("EXPIRED", "Expired"),
                            ("WRITTEN_OFF", "Written off"),
                        ],
                        db_index=True,
                        default="IN_PROGRESS",
                        max_length=12,
                    ),
                ),
                ("soak_started_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expected_yield",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=14, null=True
                    ),
                ),
                (
                    "actual_yield",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Measured, not assumed. The number nobody has today.",
                        max_digits=14,
                        null=True,
                    ),
                ),
                (
                    "matured_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "ambient_temp_f",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Recorded so fermentation time can be tuned across the seasons.",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="catalog.item",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="core.location",
                    ),
                ),
                (
                    "produced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="catalog.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "production batches",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="BatchSplit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "child",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="split_from",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="splits",
                        to="production.productionbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=160)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputs",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "from_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consumed_by",
                        to="production.productionbatch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.item",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="productionbatch",
            index=models.Index(
                fields=["item", "status", "expires_at"],
                name="production__item_id_ff1d91_idx",
            ),
        ),
    ]
