# Generated by Django 5.2.17 on 2026-09-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_count_every_defaults'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='yield_entered_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.itemmeasure'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='yield_entered_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='productioninput',
            name='entered_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.itemmeasure'),
        ),
        migrations.AddField(
            model_name='productioninput',
            name='entered_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True),
        ),
    ]
