# Generated by Django 5.2.17 on 2026-09-16 04:53

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PosItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("pos_name", models.CharField(max_length=200, unique=True)),
                ("pos_category", models.CharField(blank=True, max_length=120)),
                (
                    "is_modifier",
                    models.BooleanField(
                        default=False,
                        help_text="Add-ons such as extra paneer. These consume stock in their own right.",
                    ),
                ),
                (
                    "ignore",
                    models.BooleanField(
                        default=False,
                        help_text="Deliberately not stock-bearing, e.g. a service charge line.",
                    ),
                ),
                ("first_seen_on", models.DateField(blank=True, null=True)),
                ("last_seen_on", models.DateField(blank=True, null=True)),
                ("mapped_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The dish this sells. Null means unmapped -- it will not deplete anything.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pos_items",
                        to="catalog.item",
                    ),
                ),
                (
                    "mapped_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["pos_name"],
            },
        ),
        migrations.CreateModel(
            name="SalesImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("business_date", models.DateField(db_index=True)),
                ("source_filename", models.CharField(blank=True, max_length=255)),
                (
                    "source_sha256",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IMPORTED", "Imported"),
                            ("POSTED", "Posted to stock"),
                            ("FAILED", "Failed"),
                            ("SUPERSEDED", "Superseded by a later import"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("rows_read", models.PositiveIntegerField(default=0)),
                ("rows_mapped", models.PositiveIntegerField(default=0)),
                ("rows_unmapped", models.PositiveIntegerField(default=0)),
                ("error_detail", models.TextField(blank=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales_imports",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date"],
            },
        ),
        migrations.CreateModel(
            name="SalesImportLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_sold", models.DecimalField(decimal_places=4, max_digits=14)),
                (
                    "quantity_voided",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "quantity_comped",
                    models.DecimalField(
                        decimal_places=4, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "raw_row",
                    models.JSONField(
                        default=dict,
                        help_text="The original CSV row, kept so an import can always be explained.",
                    ),
                ),
                (
                    "pos_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_lines",
                        to="sales.positem",
                    ),
                ),
                (
                    "sales_import",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="sales.salesimport",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="positem",
            index=models.Index(fields=["item"], name="sales_posit_item_id_a888c9_idx"),
        ),
        migrations.AddConstraint(
            model_name="salesimport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "SUPERSEDED"), _negated=True),
                fields=("business_date", "location"),
                name="one_live_import_per_date",
            ),
        ),
    ]
