# Generated by Django 5.2.17 on 2026-09-16 05:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positem',
            name='active_on_pos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='positem',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='positem',
            name='quantity_per_sale',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), help_text="In the target item's base unit. 1 for dishes; set for sized portions.", max_digits=14),
        ),
        migrations.AddField(
            model_name='positem',
            name='revenue_class',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
