# Generated by Django 5.2.17 on 2026-09-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_positem_active_on_pos_positem_default_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='positem',
            name='group_key',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
