# Generated by Django 5.2.17 on 2026-09-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_backfill_group_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='positem',
            name='portion_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
