# Generated by Django 5.2.17 on 2026-10-06 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_item_changes_daily'),
        ('sales', '0006_backfill_portion_confirmed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThaliDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField(unique=True)),
                ('said', models.TextField(blank=True, help_text='What the owner typed, kept as they wrote it.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date'],
            },
        ),
        migrations.CreateModel(
            name='ThaliLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ounces', models.DecimalField(decimal_places=4, help_text='Per plate, as the kitchen says it.', max_digits=14)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.item')),
                ('thali_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.thaliday')),
            ],
            options={
                'ordering': ['thali_day', 'sort_order'],
                'constraints': [models.UniqueConstraint(fields=('thali_day', 'item'), name='thali_item_once_a_day')],
            },
        ),
    ]
