# Generated by Django 5.2.17 on 2026-09-26 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tablet_added_people'),
        ('stock', '0002_count_in_kitchen_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='core.supplier'),
        ),
    ]
