# Generated by Django 5.2.17 on 2026-09-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(blank=True, help_text='For alerts. In full international form: +1818…', max_length=24),
        ),
        migrations.AddField(
            model_name='user',
            name='receives_alerts',
            field=models.BooleanField(default=True, help_text='Unticking stops messages without removing the number.'),
        ),
    ]
