# Generated by Django 5.2.17 on 2026-09-24 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_position_and_pin_lockout'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Added on the tablet and not yet confirmed by an owner.'),
        ),
        migrations.AddField(
            model_name='user',
            name='possible_duplicate_of',
            field=models.ForeignKey(blank=True, help_text='The existing person they said they were not, when adding themselves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
