# Generated by Django 5.2.17 on 2026-09-17 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_rename_measure_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('heading', models.CharField(blank=True, max_length=160)),
                ('text', models.TextField()),
                ('length', models.PositiveIntegerField(default=0, help_text='Tokens, for ranking.')),
            ],
            options={
                'ordering': ['record', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=400)),
                ('answer', models.TextField(blank=True)),
                ('outcome', models.CharField(choices=[('ANSWERED', 'Answered from the records'), ('NOT_RECORDED', 'Not recorded — ask the chef'), ('REFUSED', 'Refused — sending was not permitted')], db_index=True, max_length=14)),
                ('answered_by', models.CharField(blank=True, help_text='Which engine wrote the wording.', max_length=40)),
                ('chef_note', models.CharField(blank=True, max_length=300)),
                ('was_wrong', models.BooleanField(default=False)),
                ('asked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('passages', models.ManyToManyField(blank=True, related_name='answers', to='knowledge.passage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(help_text="The chef's own words. Markdown.")),
                ('source', models.CharField(choices=[('CHEF', 'Written with the head chef'), ('DOCUMENT', 'From a document the kitchen supplied'), ('BATCH_NOTE', 'From a note made while cooking'), ('SYSTEM', "Derived from the system's own records")], default='CHEF', max_length=12)),
                ('origin', models.CharField(blank=True, help_text='Where it came from, so it can be traced back.', max_length=200)),
                ('language', models.CharField(default='en', max_length=8)),
                ('captured_on', models.DateField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, help_text='The dish or component this is about, where there is one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge', to='catalog.item')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='passage',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='knowledge.record'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['item'], name='knowledge_r_item_id_0a4cdb_idx'),
        ),
        migrations.AddConstraint(
            model_name='passage',
            constraint=models.UniqueConstraint(fields=('record', 'ordinal'), name='uniq_passage_ordinal'),
        ),
    ]
