# Generated by Django 5.2.17 on 2026-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='serving_note',
            field=models.CharField(blank=True, help_text='How that was arrived at, e.g. “one chafer fills 40 thali bowls”.', max_length=200),
        ),
        migrations.AddField(
            model_name='record',
            name='servings_per_batch',
            field=models.PositiveIntegerField(blank=True, help_text='Plates from one batch. Ask the chef — never estimate it.', null=True),
        ),
    ]
