# Generated by Django 5.2.17 on 2026-10-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_record_servings_per_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='approved_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
