"""
Regenerate the documentation that can be derived from the code.

    python manage.py docs           write docs/
    python manage.py docs --check   fail if anything is out of date

Documentation kept by hand in a separate folder is stale within a fortnight.
Nobody is lying; it is simply that the code changes in one commit and the
document changes in nobody's. So the parts that CAN be derived are derived,
and CI runs --check, which means a model change with no matching doc change
fails the build. The document cannot drift, because drifting breaks
something.

Generated here:

  docs/data-model.md    every table and field, from the models themselves
  docs/traceability.md  each numbered requirement against the code and tests
                        that implement it

Written by hand, because judgement does not generate:

  docs/architecture.md  how the pieces fit and why
  docs/runbook.md       what to do when something breaks
  docs/adr/             decisions, and what they cost
"""

import json
import re
from collections import defaultdict
from pathlib import Path

from django.apps import apps as django_apps
from django.conf import settings
from django.core.management.base import BaseCommand

OUR_APPS = ["core", "catalog", "stock", "production", "sales", "labour"]
REF_RE = re.compile(r"\b((?:FR|NFR|D|BO|NFR)-\d+)\b")

BANNER = "<!-- GENERATED by `python manage.py docs`. Do not edit by hand. -->\n\n"


def field_type(field) -> str:
    name = field.get_internal_type().replace("Field", "")
    if field.is_relation and field.related_model:
        return f"{name} → {field.related_model._meta.object_name}"
    if getattr(field, "max_digits", None):
        return f"{name}({field.max_digits},{field.decimal_places})"
    if getattr(field, "max_length", None):
        return f"{name}({field.max_length})"
    return name


def first_sentence(text: str, limit: int = 160) -> str:
    text = " ".join((text or "").split())
    return text[: limit - 1] + "…" if len(text) > limit else text


class Command(BaseCommand):
    help = "Regenerate derived documentation."

    def add_arguments(self, parser):
        parser.add_argument("--check", action="store_true", help="Fail if anything is stale.")

    def handle(self, *args, **options):
        docs = Path(settings.BASE_DIR) / "docs"
        docs.mkdir(exist_ok=True)

        outputs = {
            docs / "data-model.md": self.data_model(),
            docs / "traceability.md": self.traceability(),
        }

        stale = []
        for path, content in outputs.items():
            # Exactly one newline at the end, which is what the end-of-file
            # hook leaves behind. Anything else and the hook and `--check`
            # disagree, so a freshly generated file fails CI once committed.
            content = content.rstrip("\n") + "\n"
            current = path.read_text() if path.exists() else ""
            if current != content:
                stale.append(path.name)
                if not options["check"]:
                    path.write_text(content)

        if options["check"]:
            if stale:
                self.stderr.write(
                    self.style.ERROR(
                        "Documentation is out of date: " + ", ".join(stale) + "\n"
                        "Run `python manage.py docs` and commit the result."
                    )
                )
                raise SystemExit(1)
            self.stdout.write(self.style.SUCCESS("Documentation is up to date."))
            return

        if stale:
            self.stdout.write(self.style.SUCCESS("Rewrote: " + ", ".join(stale)))
        else:
            self.stdout.write("Already up to date.")

    # ------------------------------------------------------------------
    def data_model(self) -> str:
        out = [BANNER, "# Data model\n\n"]
        out.append(
            "Every table in the system, taken from the models themselves.\n\n"
            "Two things to know before reading:\n\n"
            "- **`StockMovement` is append-only.** Quantity on hand is the sum of its rows.\n"
            "  Nothing edits a balance; everything writes movements. See ADR 0001.\n"
            "- **Raw materials, prepared components and dishes are all `Item`**, differing\n"
            "  only by `kind`. One recursive routine explodes a sale down to raw\n"
            "  materials. See ADR 0002.\n\n"
        )

        for label in OUR_APPS:
            config = django_apps.get_app_config(label)
            models = sorted(config.get_models(), key=lambda m: m._meta.object_name)
            if not models:
                continue
            out.append(f"## `{label}`\n\n")
            for model in models:
                meta = model._meta
                out.append(f"### {meta.object_name}\n\n")
                doc = (model.__doc__ or "").strip()
                if doc and not doc.startswith(meta.object_name):
                    out.append(f"{first_sentence(doc, 300)}\n\n")
                out.append("| Field | Type | Null | Notes |\n|---|---|---|---|\n")
                for field in meta.get_fields():
                    if not hasattr(field, "get_internal_type"):
                        continue
                    note = first_sentence(getattr(field, "help_text", "") or "", 110)
                    if getattr(field, "choices", None):
                        values = ", ".join(str(c[0]) for c in field.choices[:6])
                        note = (note + " " if note else "") + f"_{values}_"
                    null = "yes" if field.null else ""
                    out.append(f"| `{field.name}` | {field_type(field)} | {null} | {note} |\n")
                out.append("\n")
        return "".join(out)

    # ------------------------------------------------------------------
    def traceability(self) -> str:
        base = Path(settings.BASE_DIR)
        spec_path = base / "docs" / "requirements.json"
        spec = json.loads(spec_path.read_text()) if spec_path.exists() else []

        code_refs = defaultdict(set)
        test_refs = defaultdict(set)

        for path in sorted(base.glob("apps/**/*.py")) + sorted(base.glob("templates/**/*.html")):
            if "__pycache__" in str(path) or "/migrations/" in str(path):
                continue
            rel = path.relative_to(base)
            try:
                text = path.read_text()
            except UnicodeDecodeError:
                continue
            for ref in REF_RE.findall(text):
                (test_refs if "/tests/" in str(rel) else code_refs)[ref].add(str(rel))

        out = [BANNER, "# Requirements traceability\n\n"]
        out.append(
            "Each numbered requirement from the Discovery & Requirements Report against\n"
            "the code that implements it and the tests that hold it in place.\n\n"
            "**A requirement is only marked as covered when a file actually names it.**\n"
            "Write `FR-403` in a docstring, a comment or a test name and it appears here.\n"
            "Nothing is inferred from a function looking roughly relevant — that would\n"
            "make this table reassuring and wrong, which is worse than an empty one.\n\n"
        )

        done = sum(1 for r in spec if r["ref"] in code_refs)
        tested = sum(1 for r in spec if r["ref"] in test_refs)
        out.append(
            f"**{done} of {len(spec)}** requirements referenced in code · **{tested}** covered by a test.\n\n"
        )

        by_module = defaultdict(list)
        for row in spec:
            by_module[(row["module"], row["module_name"])].append(row)

        for (module, name), rows in by_module.items():
            out.append(f"## {module} — {name}\n\n")
            out.append("| Ref | Requirement | Priority | Code | Tests |\n|---|---|---|---|---|\n")
            for row in rows:
                ref = row["ref"]
                code = "<br>".join(f"`{p}`" for p in sorted(code_refs.get(ref, []))) or "—"
                tests = "<br>".join(f"`{p}`" for p in sorted(test_refs.get(ref, []))) or "—"
                text = row["text"].replace("|", "\\|")
                out.append(f"| **{ref}** | {text} | {row['priority']} | {code} | {tests} |\n")
            out.append("\n")
        return "".join(out)
