# Generated by Django 5.2.17 on 2026-09-16 04:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(default="Standard 3–5pm closure", max_length=60),
                ),
                ("start_time", models.TimeField(default=datetime.time(15, 0))),
                ("end_time", models.TimeField(default=datetime.time(17, 0))),
                ("applies_monday", models.BooleanField(default=False)),
                ("applies_tuesday", models.BooleanField(default=True)),
                ("applies_wednesday", models.BooleanField(default=True)),
                ("applies_thursday", models.BooleanField(default=True)),
                ("applies_friday", models.BooleanField(default=True)),
                ("applies_saturday", models.BooleanField(default=True)),
                ("applies_sunday", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clocked_in_at", models.DateTimeField(db_index=True)),
                ("clocked_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clock_in_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="clockin/%Y/%m/"
                    ),
                ),
                (
                    "worked_through_break",
                    models.BooleanField(
                        default=False,
                        help_text="Exception: the standard closure was not taken.",
                    ),
                ),
                (
                    "break_override_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_catering_event", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "break_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="labour.breakpolicy",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="core.location",
                    ),
                ),
            ],
            options={
                "ordering": ["-clocked_in_at"],
            },
        ),
        migrations.CreateModel(
            name="ShiftEdit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("field_name", models.CharField(max_length=40)),
                ("old_value", models.CharField(blank=True, max_length=80)),
                ("new_value", models.CharField(blank=True, max_length=80)),
                ("reason", models.CharField(max_length=240)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edits",
                        to="labour.shift",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["employee", "clocked_in_at"],
                name="labour_shif_employe_97deba_idx",
            ),
        ),
    ]
