# Generated by Django 5.2.17 on 2026-09-24 18:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def refuse_if_shifts_exist(apps, schema_editor):
    """
    ADR 0008 removed the break deduction when no real shift had been
    recorded. The placeholder business date and period below are only safe
    on an empty table; on real records they would be wrong without anybody
    noticing, so this stops rather than guessing.
    """
    if apps.get_model("labour", "Shift").objects.exists():
        raise RuntimeError(
            "Shifts exist. Their business date and period must be derived from "
            "clocked_in_at before this migration can run -- see ADR 0008."
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_position_and_pin_lockout'),
        ('labour', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(refuse_if_shifts_exist, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], max_length=8)),
                ('weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Leave empty for every day.', null=True)),
                ('starts_at', models.TimeField()),
                ('ends_at', models.TimeField()),
            ],
            options={
                'ordering': ['position', 'weekday', 'starts_at'],
            },
        ),
        migrations.RemoveField(
            model_name='breakpolicy',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='break_policy',
        ),
        migrations.RemoveIndex(
            model_name='shift',
            name='labour_shif_employe_97deba_idx',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='break_override_minutes',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='worked_through_break',
        ),
        migrations.AddField(
            model_name='shift',
            name='business_date',
            field=models.DateField(db_index=True, default=datetime.date(2026, 9, 24)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='period',
            field=models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening')], default='MORNING', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.position'),
        ),
        migrations.AddField(
            model_name='shift',
            name='scheduled_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='scheduled_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftedit',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edits', to='labour.shift'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['employee', 'business_date'], name='labour_shif_employe_403455_idx'),
        ),
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.CheckConstraint(condition=models.Q(('clocked_out_at__isnull', True), ('clocked_out_at__gt', models.F('clocked_in_at')), _connector='OR'), name='shift_ends_after_start'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='core.position'),
        ),
        migrations.DeleteModel(
            name='BreakPolicy',
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(fields=('position', 'period', 'weekday'), name='uniq_template_per_position_period_day'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('weekday__isnull', True)), fields=('position', 'period'), name='uniq_everyday_template_per_position_period'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='template_ends_after_start'),
        ),
    ]
