# Generated by Django 5.2.17 on 2026-09-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_separate_morning_and_evening_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='source',
            field=models.CharField(choices=[('CLOCK', 'Clocked in and out'), ('ENTERED', 'Entered by the worker')], default='CLOCK', max_length=8),
        ),
    ]
