# Generated by Django 5.2.17 on 2026-09-24 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0003_shift_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_up_to', models.DateField(help_text='Every unpaid shift up to and including this day.')),
                ('paid_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=240)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=240)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_up_to', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shift',
            name='pay_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='labour.payrun'),
        ),
        migrations.CreateModel(
            name='PayRunLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_day', models.DateField()),
                ('last_day', models.DateField()),
                ('shift_count', models.PositiveIntegerField()),
                ('minutes', models.PositiveIntegerField()),
                ('morning_minutes', models.PositiveIntegerField()),
                ('evening_minutes', models.PositiveIntegerField()),
                ('catering_minutes', models.PositiveIntegerField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pay_lines', to=settings.AUTH_USER_MODEL)),
                ('pay_run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='labour.payrun')),
            ],
            options={
                'ordering': ['pay_run', 'employee__display_name'],
                'constraints': [models.UniqueConstraint(fields=('pay_run', 'employee'), name='one_line_per_person_per_payment')],
            },
        ),
    ]
