# Generated by Django 5.2.17 on 2026-09-25 18:04

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0004_pay_runs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shift',
            options={'base_manager_name': 'all_objects', 'default_manager_name': 'all_objects', 'ordering': ['-clocked_in_at']},
        ),
        migrations.AlterModelManagers(
            name='shift',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AddField(
            model_name='shift',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='source',
            field=models.CharField(choices=[('CLOCK', 'Clocked in and out'), ('ENTERED', 'Entered by the worker'), ('OWNER', 'Entered by an owner')], default='CLOCK', max_length=8),
        ),
    ]
