# Generated by Django 5.2.17 on 2026-10-06 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tablet_added_people'),
        ('labour', '0005_owner_entries_and_cancelled_shifts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_date', models.DateField(db_index=True)),
                ('cover', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('BOTH', 'Morning and evening')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=120)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.position')),
            ],
            options={
                'ordering': ['business_date', 'position__sort_order', 'position__name'],
                'constraints': [models.UniqueConstraint(fields=('business_date', 'employee'), name='one_assignment_per_person_per_day')],
            },
        ),
    ]
