"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(int(default))).strip().lower() in {"1", "true", "yes", "on"}


# The secret key never lives in the repository. Locally it comes from .env
# (which is gitignored); on a server it comes from the environment. There is
# no default, on purpose -- a missing key should stop the process, not
# silently fall back to one that is in everybody's git history.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
DEBUG = env_bool("DJANGO_DEBUG", default=False)

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-key-not-for-any-server"
    else:
        raise RuntimeError("DJANGO_SECRET_KEY is not set. Refusing to start with DEBUG off and no key.")

# In development, accept any host so the app can be opened from a phone on
# the same wi-fi without knowing the laptop's address in advance. In
# production the hosts are listed explicitly and nothing else is served.
if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# Django 4+ checks the Origin header on unsafe requests. A phone reaching the
# laptop over the LAN sends its own address, so trust the private ranges in
# development only.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
# On Vercel the app's own addresses come from Vercel itself: the production
# address (woodlands-ims.vercel.app or the restaurant's domain) and the
# address of this particular deployment. Nothing to type in by hand.
if os.environ.get("VERCEL"):
    for name in ("VERCEL_PROJECT_PRODUCTION_URL", "VERCEL_URL", "VERCEL_BRANCH_URL"):
        host = os.environ.get(name, "").strip()
        if host and host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)
            CSRF_TRUSTED_ORIGINS.append(f"https://{host}")

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://192.168.*.*:8000",
        "http://10.*.*.*:8000",
        "http://172.16.*.*:8000",
    ]


# Application definition

INSTALLED_APPS = [
    "apps.core",
    "apps.catalog",
    "apps.stock",
    "apps.production",
    "apps.sales",
    "apps.notify",
    "apps.knowledge",
    "apps.labour",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves the CSS from the app itself, compressed, so the server needs no
    # separate web server in front of it for files.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "apps.core.context_processors.nav",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# On a server, DATABASE_URL points at PostgreSQL (the host provides it, e.g.
# postgres://user:password@host:5432/woodlands). Locally, the SQLite file.
if os.environ.get("DATABASE_URL"):
    import dj_database_url

    DATABASES = {"default": dj_database_url.config(conn_max_age=600, conn_health_checks=True)}
elif env_bool("VERCEL"):
    # The bundle is read-only and every request may be a fresh machine: a
    # SQLite file there would lose everything. Stop, and say why.
    raise RuntimeError("DATABASE_URL is not set. On Vercel the database must be PostgreSQL.")
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Los_Angeles"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Where `collectstatic` gathers everything for the server. Not in git.
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# On Vercel there is no build step for `collectstatic`, and the bundle is
# read-only: WhiteNoise serves the CSS straight from where it lives instead.
# Vercel sets VERCEL=1 in every function.
WHITENOISE_USE_FINDERS = env_bool("VERCEL")

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "core.User"

# ---------------------------------------------------------------------------
# Alerts
# ---------------------------------------------------------------------------
#
# Messages are always RECORDED -- written to the database -- and only then
# carried by a channel. The channel is configuration, not code: nothing in the
# stock or production modules knows or cares which one is in use.
#
# The default is "recorded", which sends nothing. Text messages cost the client
# money every month, so they stay switched off until the owners have agreed to
# that, and switching them on is one environment variable rather than a
# release.
NOTIFY_CHANNEL = os.environ.get("NOTIFY_CHANNEL", "RECORDED")

TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.environ.get("TWILIO_FROM_NUMBER", "")


# ---------------------------------------------------------------------------
# The kitchen's knowledge base
# ---------------------------------------------------------------------------
#
# Retrieval always runs here, on this machine, over the restaurant's own
# records. Only the wording of an answer can involve an outside service, and
# only when BOTH of the following are true:
#
#   KNOWLEDGE_ENGINE=claude     somebody chose it
#   KNOWLEDGE_CONSENT=1         the client agreed, informed, in advance
#
# The second is not a duplicate of the first. Configuration gets changed by
# accident; consent is the client's decision, and the code refuses to send
# recipes outside without it whatever the engine is set to (FR-1013).
KNOWLEDGE_ENGINE = os.environ.get("KNOWLEDGE_ENGINE", "records")
KNOWLEDGE_CONSENT = env_bool("KNOWLEDGE_CONSENT", default=False)
KNOWLEDGE_API_KEY = os.environ.get("KNOWLEDGE_API_KEY", "")

# Where Claude is reached (apps.core.ai). "vertex": the restaurant's own Google
# Cloud project, billed there -- the owners' choice. "anthropic": an Anthropic
# API key (KNOWLEDGE_API_KEY). Same model either way.
AI_PROVIDER = os.environ.get("AI_PROVIDER", "anthropic").strip().lower()
GCP_PROJECT_ID = os.environ.get("GCP_PROJECT_ID", "")
GCP_REGION = os.environ.get("GCP_REGION", "global")
# A service account's JSON key, pasted whole into the host's settings. Not
# needed on a laptop signed in with `gcloud auth application-default login`.
GCP_SERVICE_ACCOUNT_JSON = os.environ.get("GCP_SERVICE_ACCOUNT_JSON", "")
KNOWLEDGE_MODEL = os.environ.get("KNOWLEDGE_MODEL", "claude-opus-5-5")


# ---------------------------------------------------------------------------
# On a server: HTTPS only
# ---------------------------------------------------------------------------
#
# DJANGO_HTTPS=1 on any server (the container image sets it). It is a switch
# of its own rather than "whenever DEBUG is off" so the test suite and CI --
# which run without DEBUG -- are not redirected to an https:// they cannot
# reach. `manage.py check --deploy` with DJANGO_HTTPS=1 passes clean.
HTTPS = env_bool("DJANGO_HTTPS", default=False)
if HTTPS:
    # The host terminates TLS and forwards plain HTTP with this header.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    # The platform's health check comes from inside, over plain HTTP.
    SECURE_REDIRECT_EXEMPT = [r"^healthz$"]
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Browsers remember "HTTPS only" for this long. 30 days to start; raise
    # to a year once the address is settled.
    SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_HSTS_SECONDS", 60 * 60 * 24 * 30))
    # Deliberately off, and silenced so the checklist stays clean: on a
    # host's shared address (woodlands.onrender.com and the like) the other
    # subdomains are not ours, and a preload listing takes months to undo.
    # Revisit only with the restaurant's own domain.
    SILENCED_SYSTEM_CHECKS = ["security.W005", "security.W021"]

# ---------------------------------------------------------------------------
# Yesterday's sales, by email
# ---------------------------------------------------------------------------
#
# The secret part of the address the email service posts Shift4's daily report
# to: /sales/inbound/<this>/. Long and random; empty switches the address off.
#   python -c "import secrets;print(secrets.token_urlsafe(32))"
SALES_INBOUND_TOKEN = os.environ.get("SALES_INBOUND_TOKEN", "")

# A "set your password" link for a new owner works once and for this long.
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24 * 3

# The address links are built on when they are printed rather than clicked,
# e.g. https://woodlands.example.com. Only used by `manage.py invite_owner`.
SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000").rstrip("/")

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"
