"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    return os.environ.get(name, str(int(default))).strip().lower() in {"1", "true", "yes", "on"}


# The secret key never lives in the repository. Locally it comes from .env
# (which is gitignored); on a server it comes from the environment. There is
# no default, on purpose -- a missing key should stop the process, not
# silently fall back to one that is in everybody's git history.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
DEBUG = env_bool("DJANGO_DEBUG", default=False)

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-key-not-for-any-server"
    else:
        raise RuntimeError("DJANGO_SECRET_KEY is not set. Refusing to start with DEBUG off and no key.")

# In development, accept any host so the app can be opened from a phone on
# the same wi-fi without knowing the laptop's address in advance. In
# production the hosts are listed explicitly and nothing else is served.
if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()]

# Django 4+ checks the Origin header on unsafe requests. A phone reaching the
# laptop over the LAN sends its own address, so trust the private ranges in
# development only.
CSRF_TRUSTED_ORIGINS = [
    o.strip() for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o.strip()
]
if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://192.168.*.*:8000",
        "http://10.*.*.*:8000",
        "http://172.16.*.*:8000",
    ]


# Application definition

INSTALLED_APPS = [
    "apps.core",
    "apps.catalog",
    "apps.stock",
    "apps.production",
    "apps.sales",
    "apps.notify",
    "apps.knowledge",
    "apps.labour",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Los_Angeles"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


AUTH_USER_MODEL = "core.User"

# ---------------------------------------------------------------------------
# Alerts
# ---------------------------------------------------------------------------
#
# Messages are always RECORDED -- written to the database -- and only then
# carried by a channel. The channel is configuration, not code: nothing in the
# stock or production modules knows or cares which one is in use.
#
# The default is "recorded", which sends nothing. Text messages cost the client
# money every month, so they stay switched off until the owners have agreed to
# that, and switching them on is one environment variable rather than a
# release.
NOTIFY_CHANNEL = os.environ.get("NOTIFY_CHANNEL", "RECORDED")

TWILIO_ACCOUNT_SID = os.environ.get("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.environ.get("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM_NUMBER = os.environ.get("TWILIO_FROM_NUMBER", "")


# ---------------------------------------------------------------------------
# The kitchen's knowledge base
# ---------------------------------------------------------------------------
#
# Retrieval always runs here, on this machine, over the restaurant's own
# records. Only the wording of an answer can involve an outside service, and
# only when BOTH of the following are true:
#
#   KNOWLEDGE_ENGINE=claude     somebody chose it
#   KNOWLEDGE_CONSENT=1         the client agreed, informed, in advance
#
# The second is not a duplicate of the first. Configuration gets changed by
# accident; consent is the client's decision, and the code refuses to send
# recipes outside without it whatever the engine is set to (FR-1013).
KNOWLEDGE_ENGINE = os.environ.get("KNOWLEDGE_ENGINE", "records")
KNOWLEDGE_CONSENT = env_bool("KNOWLEDGE_CONSENT", default=False)
KNOWLEDGE_API_KEY = os.environ.get("KNOWLEDGE_API_KEY", "")
KNOWLEDGE_MODEL = os.environ.get("KNOWLEDGE_MODEL", "claude-sonnet-4-5")


LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "login"
