# Generated by Django 5.2.17 on 2026-09-16 04:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=48, unique=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("RAW", "Raw material"),
                            ("PREPARED", "Prepared component"),
                            ("DISH", "Menu dish"),
                            ("PACKAGING", "Packaging"),
                            ("CONSUMABLE", "Consumable"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "is_stocked",
                    models.BooleanField(
                        default=True,
                        help_text="Dishes are not stocked; raw materials and bases are.",
                    ),
                ),
                (
                    "shelf_life_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_allergen_relevant", models.BooleanField(default=False)),
                ("allergen_notes", models.CharField(blank=True, max_length=240)),
                (
                    "current_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Weighted average, per base unit.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ItemAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(max_length=160)),
                ("source", models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "item categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ParLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                (
                    "quantity_in_base_units",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "is_approximate",
                    models.BooleanField(
                        default=False,
                        help_text="For things like a bunch of curry leaves, where the weight is nominal.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["item", "name"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveSmallIntegerField(default=1)),
                (
                    "yield_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="How much this recipe produces, in the item's base unit.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("method", models.TextField(blank=True)),
                ("doneness_cues", models.TextField(blank=True)),
                ("common_mistakes", models.TextField(blank=True)),
                ("substitutions", models.TextField(blank=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["item", "-version"],
            },
        ),
        migrations.CreateModel(
            name="RecipeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="In the component's base unit, per one yield of the parent recipe.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=160)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["recipe", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=40)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("WEIGHT", "Weight"),
                            ("VOLUME", "Volume"),
                            ("COUNT", "Count"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "to_canonical",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1E-8"))
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "code"],
            },
        ),
    ]
