# Generated by Django 5.2.17 on 2026-09-17 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_item_measure'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemmeasure',
            name='uniq_purchase_unit',
        ),
        migrations.AddConstraint(
            model_name='itemmeasure',
            constraint=models.UniqueConstraint(fields=('item', 'name', 'supplier'), name='uniq_item_measure'),
        ),
    ]
