# Generated by Django 5.2.17 on 2026-09-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_vessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='count_every',
            field=models.CharField(blank=True, choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('NEVER', 'Not counted')], help_text="Which count this item is on. Left empty, it follows the kitchen's rule for its kind.", max_length=8),
        ),
    ]
