# Generated by Django 5.2.17 on 2026-10-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_count_every_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='changes_daily',
            field=models.BooleanField(default=False),
        ),
    ]
