# Generated by Django 5.2.17 on 2026-09-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('LOW_STOCK', 'An item is running out'), ('BASE_LOW', 'A base or batter is running out'), ('ASSIGNMENT', 'Somebody has been asked to make something'), ('EXPIRING', 'A batch is close to its use-by')], db_index=True, max_length=12)),
                ('body', models.TextField(help_text='What the person will actually read.')),
                ('dedupe_key', models.CharField(max_length=180, unique=True)),
                ('channel', models.CharField(choices=[('SMS', 'Text message'), ('SLACK', 'Slack'), ('EMAIL', 'Email'), ('RECORDED', 'Recorded only')], default='RECORDED', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting to be sent'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SUPPRESSED', 'Not sent — the person has alerts turned off')], db_index=True, default='PENDING', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('sent_to', models.CharField(blank=True, max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='notify_noti_recipie_56f8c5_idx')],
            },
        ),
    ]
