# Generated by Django 5.2.17 on 2026-10-06 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('LOW_STOCK', 'An item is running out'), ('BASE_LOW', 'A base or batter is running out'), ('ASSIGNMENT', 'Somebody has been asked to make something'), ('EXPIRING', 'A batch is close to its use-by'), ('SALES', "A day's sales came in by email")], db_index=True, max_length=12),
        ),
    ]
